export { default as Home }  from '../pages/home/Home'
export  { default as Navigation } from './navigation/Navigation'
export  { default as Shop }  from '../pages/shop/Shop'
export { default as SignUp } from '../pages/authentication/SignUp'
export { default as SignIn } from '../pages/authentication/SignIn'
export { default as Authentication } from '../pages/authentication'
export { default as Checkout } from '../pages/checkout/checkout'